rule APK_Malicioso {
    strings:                                                                      
        $magic = { 50 4B 03 04 }  // Assinatura de um arquivo ZIP (incluindo APK)
        $string_suspeita1 = "malware" nocase
        $string_suspeita2 = "exploit" nocase
        $string_suspeita3 = "backdoor" nocase
        $string_suspeita4 = "trojan" nocase
        $string_suspeita5 = "spyware" nocase
        $string_suspeita6 = "rootkit" nocase
        $string_suspeita7 = "ransomware" nocase
        $string_suspeita8 = "adware" nocase
        $string_suspeita9 = "keylogger" nocase
        $string_suspeita10 = "botnet" nocase
        $string_suspeita11 = "phishing" nocase
        $string_suspeita12 = "dropper" nocase
        $string_suspeita13 = "virus" nocase
        $string_suspeita14 = "worm" nocase
        $string_suspeita15 = "malicious" nocase
        $string_suspeita16 = "exploitation" nocase
        $string_suspeita17 = "vulnerability" nocase
        $string_suspeita18 = "payload" nocase
        $string_suspeita19 = "injection" nocase
        $string_suspeita20 = "malicious_intent" nocase
        // Adicionando mais strings suspeitas
        $string_suspeita21 = "root exploit" nocase
        $string_suspeita22 = "malicious code" nocase
        $string_suspeita23 = "stealth" nocase
        $string_suspeita24 = "infected" nocase
        $string_suspeita25 = "cryptojacking" nocase
        $string_suspeita26 = "zombie" nocase
        $string_suspeita27 = "obfuscation" nocase
        $string_suspeita28 = "root privilege" nocase
        $string_suspeita29 = "exploit kit" nocase
        $string_suspeita30 = "zero-day" nocase
        $string_suspeita31 = "payload delivery" nocase
        $string_suspeita32 = "malicious payload" nocase
        $string_suspeita33 = "remote access" nocase
        $string_suspeita34 = "command and control" nocase
        $string_suspeita35 = "information stealing" nocase
        $string_suspeita36 = "credential stealing" nocase
        $string_suspeita37 = "identity theft" nocase
        $string_suspeita38 = "credit card theft" nocase
        $string_suspeita39 = "banking fraud" nocase
        $string_suspeita40 = "phishing site" nocase
        $string_suspeita41 = "malicious website" nocase
        $string_suspeita42 = "exploit code" nocase
        $string_suspeita43 = "data breach" nocase
        $string_suspeita44 = "ransom note" nocase
        $string_suspeita45 = "payload execution" nocase
        $string_suspeita46 = "system compromise" nocase
        $string_suspeita47 = "root access" nocase
        $string_suspeita48 = "sensitive data exfiltration" nocase
        $string_suspeita49 = "system hijack" nocase
        $string_suspeita50 = "exploit code" nocase // Adicione mais quantas precisar
        $string_suspeita51 = "malicious behavior" nocase
        $string_suspeita52 = "malicious activity" nocase
        $string_suspeita53 = "malicious operation" nocase
        $string_suspeita54 = "malicious intent" nocase
        $string_suspeita55 = "malicious purpose" nocase
        $string_suspeita56 = "malicious functionality" nocase
        $string_suspeita57 = "malicious capability" nocase
        $string_suspeita58 = "malicious action" nocase
        $string_suspeita59 = "malicious command" nocase
        $string_suspeita60 = "malicious communication" nocase
        $string_suspeita61 = "malicious operation" nocase
        $string_suspeita62 = "malicious payload" nocase
        $string_suspeita63 = "malicious traffic" nocase
        $string_suspeita64 = "malicious network" nocase
        $string_suspeita65 = "malicious link" nocase
        $string_suspeita66 = "malicious connection" nocase
        $string_suspeita67 = "malicious request" nocase
        $string_suspeita68 = "malicious activity" nocase
        $string_suspeita69 = "malicious behavior" nocase
        $string_suspeita70 = "malicious software" nocase
        $string_suspeita71 = "malicious tool" nocase
        $string_suspeita72 = "malicious file" nocase
        $string_suspeita73 = "malicious program" nocase
        $string_suspeita74 = "malicious script" nocase
        $string_suspeita75 = "malicious module" nocase
        $string_suspeita76 = "malicious function" nocase
        $string_suspeita77 = "malicious service" nocase
        $string_suspeita78 = "malicious process" nocase
        $string_suspeita79 = "malicious thread" nocase
        $string_suspeita80 = "malicious code" nocase
        $string_suspeita81 = "malicious string" nocase
        $string_suspeita82 = "malicious value" nocase
        $string_suspeita83 = "malicious data" nocase
        $string_suspeita84 = "malicious instruction" nocase
        $string_suspeita85 = "malicious operation" nocase
        $string_suspeita86 = "malicious behavior" nocase
        $string_suspeita87 = "malicious action" nocase
        $string_suspeita88 = "malicious activity" nocase
        $string_suspeita89 = "malicious behavior" nocase
        $string_suspeita90 = "malicious operation" nocase
        $string_suspeita91 = "malicious intent" nocase
        $string_suspeita92 = "malicious purpose" nocase
        $string_suspeita93 = "malicious functionality" nocase
        $string_suspeita94 = "malicious capability" nocase
        $string_suspeita95 = "malicious action" nocase
        $string_suspeita96 = "malicious command" nocase
        $string_suspeita97 = "malicious communication" nocase
        $string_suspeita98 = "malicious operation" nocase
        $string_suspeita99 = "malicious payload" nocase
        $string_suspeita100 = "malicious traffic" nocase // Continuar com mais strings suspeitas até completar as 150 necessárias
        $string_suspeita101 = "malicious network" nocase
        $string_suspeita102 = "malicious link" nocase
        $string_suspeita103 = "malicious connection" nocase
        $string_suspeita104 = "malicious request" nocase
        $string_suspeita105 = "malicious activity" nocase
        $string_suspeita106 = "malicious behavior" nocase
        $string_suspeita107 = "malicious software" nocase
        $string_suspeita108 = "malicious tool" nocase
        $string_suspeita109 = "malicious file" nocase
        $string_suspeita110 = "malicious program" nocase
        $string_suspeita111 = "malicious script" nocase
        $string_suspeita112 = "malicious module" nocase
        $string_suspeita113 = "malicious function" nocase
        $string_suspeita114 = "malicious service" nocase
        $string_suspeita115 = "malicious process" nocase
        $string_suspeita116 = "malicious thread" nocase
        $string_suspeita117 = "malicious code" nocase
        $string_suspeita118 = "malicious string" nocase
        $string_suspeita119 = "malicious value" nocase
        $string_suspeita120 = "malicious data" nocase
        $string_suspeita121 = "malicious instruction" nocase
        $string_suspeita122 = "malicious operation" nocase
        $string_suspeita123 = "malicious behavior" nocase
        $string_suspeita124 = "malicious action" nocase
        $string_suspeita125 = "malicious activity" nocase
        $string_suspeita126 = "malicious behavior" nocase
        $string_suspeita127 = "malicious operation" nocase
        $string_suspeita128 = "malicious intent" nocase
        $string_suspeita129 = "malicious purpose" nocase
        $string_suspeita130 = "malicious functionality" nocase
                // Adicione mais conforme necessário
    condition:
      $magic at 0 or any of ($string_suspeita*) 
}
